build:
  image: golang
  commands:
    - go get
    - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main .
  when:
    event: push

publish:
  docker:
    username: allanks
    password: $$DOCKER_PASSWORD
    email: $$EMAIL
    repo: allanks/tas-board
    when:
      branch: master
      event: push

  ssh:
    host: $$HOST
    user: root
    commands:
      - docker login -u allanks -p $$DOCKER_PASSWORD
      - docker pull allanks/tas-board
      - echo "Stopping tas-board"
      - docker stop tas-board
      - echo "Removing tas-board"
      - docker rm tas-board
      - echo "Starting tas-board"
      - docker run -d -e "IO_TAZZY_SECRET=$$TAZZY_SECRET" -e "APP_SHORTCODE=board" -v /db/bolt/tas-board:/db --name tas-board -p 8084:8080 allanks/tas-board
    when:
      branch: master
      event: push